In [2]:
# Basic list creation
lst = [10,20,30]
print(lst)

[10, 20, 30]


In [3]:
#list can store all types even complex variable
lst = [10, True, 'Hello', 3+5j]
print(lst)
#Note list have comma in between

[10, True, 'Hello', (3+5j)]


### Working with numpy

In [6]:
# SHIFT + TAB to get documentation
import numpy as np
#Coverting list object to an array
arr = np.array(lst)
print(arr)

['10' 'True' 'Hello' '(3+5j)']


In [7]:
#Chekcing the type of array objects, All the types in array are String
print(type(arr[0]), type(arr[3]))

<class 'numpy.str_'> <class 'numpy.str_'>


In [8]:
#Passing List object directly in array and making it of type as float64
arr = np.array([1,2,3,4],dtype=np.float64) 
print(arr)
print(type(arr[0]))

#. for String we can type as 'str_'
str_arr = np.array([1,2,3,5],dtype=np.str_)
print(type(str_arr[0]))

[1. 2. 3. 4.]
<class 'numpy.float64'>
<class 'numpy.str_'>


In [9]:
#Creating Multidimensional array using reshape
print(np.array([1,2,3,4,5,6]).reshape(2,3))

[[1 2 3]
 [4 5 6]]


In [10]:
#Passing list to create array, We have to pass "list of list ==> [[],[]]"
multi = np.array([[1,2,3],[4,5,6]])
print(multi)

[[1 2 3]
 [4 5 6]]


In [11]:
#Creating using matrix function,  We have to pass "list of list ==> [[],[]]"
multi_mat = np.matrix([[4,5,6],[6,1,3]])
print(multi_mat)

[[4 5 6]
 [6 1 3]]


In [12]:
# Creating Identity Matrix, 2-D array with ones on the diagonal and zeros elsewhere.
iden_mat = np.eye(3,2,dtype=np.int64)
print(iden_mat)

[[1 0]
 [0 1]
 [0 0]]


In [13]:
#Creating a new array of given shape and type, filled with zeros.
zeros = np.zeros((3,2))
print(zeros)

[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [14]:
# New array of given shape and type, filled with ones.
ones = np.ones((4,4))
print(ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [16]:
# New array of given shape and type, filled with ones but of int type
one_int = np.ones((3,3),dtype=np.int16)
print(one_int)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [15]:
# Creating array of filled with other number instead of one. We just have to multiply with the specific number
ones_diff = np.ones((3,3),dtype=np.int32)*7
print(ones_diff)

[[7 7 7]
 [7 7 7]
 [7 7 7]]


#### Random Matrix

In [17]:
# Generating 0-1 random array of 5 elements
rand_array =  np.random.rand(5,5)
print(rand_array)

rand_array_reshape = np.random.rand(6).reshape(3,2)
print(rand_array_reshape)

[[0.63584767 0.14194963 0.14432043 0.3799196  0.38160485]
 [0.33662906 0.6242257  0.14115958 0.89603636 0.32232264]
 [0.91864689 0.93721977 0.51335771 0.45447747 0.06078182]
 [0.10427826 0.308825   0.14767574 0.14704773 0.11206084]
 [0.67017863 0.50600886 0.19984853 0.69885331 0.61336449]]
[[0.55822626 0.3004475 ]
 [0.98996528 0.02386592]
 [0.51298513 0.70995609]]


In [18]:
# Creating array of Random int (including 1 and excluding 4) total of 10 numbers
rand_int = np.random.randint(1,4,10)
print(rand_int)

[1 3 1 3 3 2 2 1 3 3]


In [50]:
#Creating matrix from random int
rand_int_20 = np.random.randint(1,101,10).reshape(5,2)
print(rand_int_20)

array([[93, 36],
       [10,  6],
       [40, 87],
       [63, 44],
       [14, 62]])

#### Array Range

In [19]:
arange = np.arange(10)
print(arange)

# np.arange(start,end-value-excluded, stepsize)
arange_start_end = np.arange(2,21,2)
print(arange_start_end)

#Shaping the array from Range function and reshape
arange_start_end_reshape = np.arange(2,21,2).reshape(5,2)
print(arange_start_end_reshape)

[0 1 2 3 4 5 6 7 8 9]
[ 2  4  6  8 10 12 14 16 18 20]
[[ 2  4]
 [ 6  8]
 [10 12]
 [14 16]
 [18 20]]


In [20]:
#Checking shape of the matrix
print(np.shape(arange_start_end_reshape))

(5, 2)


In [21]:
#It will give me the matrix rows
print(arange_start_end_reshape.shape[0])

5


In [64]:
#It will give me the matrix columns
arange_start_end_reshape.shape[1]

2

In [89]:
#Getting the minumum element from my matrix
arange_start_end_reshape.argmin()

0

In [90]:
#Getting the max element from my matrix
arange_start_end_reshape.argmax()

9

#### Indexing and Selection

In [82]:
#Creating a new array using arange function (start,end-excluded, stepsize)
aaran =  np.arange(1,22,3)
aaran

array([ 1,  4,  7, 10, 13, 16, 19])

In [83]:
#This will get me the 4th element from the array
aaran[4]

13

In [84]:
#Slicing , It will exlclude variable at 5th position
aaran[2:5]

array([ 7, 10, 13])

In [85]:
#This -2 will get the second last element from my array, likewise -1 will get me the last element of array
aaran[-2]

16

In [86]:
#Staring from zero till 5th position
aaran[:6]

array([ 1,  4,  7, 10, 13, 16])

In [95]:
#Broadcasting, Here from 0 to 4 element values are changed to 100, This is called Broadcasting
slice_array = aaran[0:5] 
slice_array[0:5] = 100
slice_array

array([100, 100, 100, 100, 100])

In [96]:
#Note above slice array is chaning the element of my main array too :(
aaran

array([100, 100, 100, 100, 100,  16,  19])

In [22]:
#To avoid changing the main array we have copy function

#Creating a new array first
my_new_array = np.arange(2,26,3)
print(my_new_array)

#Creating a copy of my main array
my_copy_array = my_new_array.copy()

#Creating a slice from my copied array
my_copy_slice = my_copy_array[:6]

#Changing the element of my sliced array
my_copy_slice[:6] = 99
print(my_copy_array)

[ 2  5  8 11 14 17 20 23]
[99 99 99 99 99 99 20 23]


In [23]:
#My main array is not changed, this time only copied array is changed
print(my_new_array)

[ 2  5  8 11 14 17 20 23]


#### Indexing of Matrices

In [116]:
# Creating a matrix of (5,4)
matx = np.arange(1,100,5).reshape(5,4)
matx

array([[ 1,  6, 11, 16],
       [21, 26, 31, 36],
       [41, 46, 51, 56],
       [61, 66, 71, 76],
       [81, 86, 91, 96]])

In [117]:
#It will print the zeroth row of the matrix
matx[0]

array([ 1,  6, 11, 16])

In [119]:
# It will give the value of 1st row and 3rd column
matx[1][3]

36

In [120]:
#This will also give the output same as above
matx[1,3]

36

In [121]:
#It will give the 1st column value of 1,2,3 row 
matx[[1,2,3],1]

array([26, 46, 66])

In [122]:
#Similary we can give multiple columns as well
matx[[1,2,3],[1,2,3]]

array([26, 51, 76])

In [123]:
# 0th and 1st Row  --- 1 column to last column
matx[:2,1:]

array([[ 6, 11, 16],
       [26, 31, 36]])

In [124]:
#Here we won't be gettiing the error it will give nothing, since 4th Column does not exist.
matx[2:5,4:7]

array([], shape=(3, 0), dtype=int32)

In [125]:
#Changing the index postion of Column and we are getting the value. So numpy does not give the error in such cases index out of bound error.
matx[2:5,3:7]

array([[56],
       [76],
       [96]])

In [126]:
#Creating a new array
arr = np.arange(1,20,3)
arr

array([ 1,  4,  7, 10, 13, 16, 19])

In [128]:
#Fetching element based on condition, element in array greater than 7 and less than 16
arr[(arr>7) & (arr<16)]

array([10, 13])

In [129]:
#Creating an array of Boolean from our condition
bool = (arr>7) & (arr<16)
bool

array([False, False, False,  True,  True, False, False])

#### Vectorised Operation

In [25]:
#Creating two different operation to perform diff operation
s_x = np.array([[1,2,3,4],[5,6,7,8]])
s_y = np.array([[10,22,33,44],[55,66,77,88]])

In [26]:
# Substracting two matrix 
print(s_y - s_x)

[[ 9 20 30 40]
 [50 60 70 80]]


In [28]:
# Adding two matrix 
print(s_y + s_x)

[[11 24 36 48]
 [60 72 84 96]]


In [29]:
# Creating a matrix of boolean by comparing existing matrix where all elements are greater than 60
print(s_y > 60)

[[False False False False]
 [False  True  True  True]]


In [30]:
# Creating a matrix where all element of 60, so that we can compare it with other matrix 
sixty_mat = np.ones((2,4))*60
print(np.less(s_y,sixty_mat))

[[ True  True  True  True]
 [ True False False False]]


In [31]:
#This is to calculate cummulative sum of both rows and column element by element
c_x = np.cumsum(s_x)
c_x

array([ 1,  3,  6, 10, 15, 21, 28, 36], dtype=int32)

In [32]:
#Cummulative sum along column since axis values is 0
c_x = np.cumsum(s_x,axis=0)
print(c_x)
print(s_x)

[[ 1  2  3  4]
 [ 6  8 10 12]]
[[1 2 3 4]
 [5 6 7 8]]


In [144]:
#Cummulative sum along row since axis value is 1
c_x = np.cumsum(s_x,axis=1)
print(c_x)
print(s_x)

[[ 1  3  6 10]
 [ 5 11 18 26]]


[[1 2 3 4]
 [5 6 7 8]]


In [34]:
# Calculating the mean of a matrix along a specifix axis. axis = 0 is for column
print(np.mean(s_y,axis = 0))
print('\n')
print(s_y)

[32.5 44.  55.  66. ]


[[10 22 33 44]
 [55 66 77 88]]
